In [ ]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import pandas as pd
!pip install matplotlib
import matplotlib as plt
import numpy as np

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [68]:
final_data_frame = pd.read_csv('final_data_frame.csv')
final_data_frame_s = final_data_frame.iloc[:, 1:]
final_data_frame_s

C3-Cz.Amplpp  C3-Cz.PowmaxFR  C3-Cz.rate  C3-Fz.Amplpp  C3-Fz.PowmaxFR  \
0      10.771740        1.759448    2.553571     11.269735        1.699437   
1     196.669607       22.868967    6.047619     64.762088        6.231080   
2       0.000000        0.000000    0.000000      0.000000        0.000000   
3       0.000000        0.000000    0.000000      0.000000        0.000000   
4      28.581092        3.163530    3.163265     49.840620        6.736548   
5       0.000000        0.000000    0.000000     12.753706        2.237521   
6      18.703224        3.219575    1.859375     18.940291        2.821125   
7       0.000000        0.000000    0.000000      0.000000        0.000000   
8      14.223828        2.123832    1.612903     15.903879        2.717828   
9      25.743377        3.482564    3.333333     29.882885        6.848453   
10      0.000000        0.000000    0.000000     10.850524        1.891749   
11     25.761279        0.834857    1.418605     40.739765       13.604004   
12     48.959123        3.510763    0.964706     43.662376        5.838032   
13     16.239587        2.219290    1.075949      0.000000        0.000000   
14     29.133594        9.877290    2.830189     32.279609        7.609799   
15      0.000000        0.000000    0.000000      0.000000        0.000000   
16     11.607268        1.461668    2.490909      0.000000        0.000000   
17      0.000000        0.000000    0.000000      0.000000        0.000000   
18     63.138583        3.994395    1.373134     88.142041        8.200465   
19      0.000000        0.000000    0.000000      0.000000        0.000000   
20      0.000000        0.000000    0.000000     13.157727        1.487593   
21    309.744112       18.020033    4.928571    326.130958       15.340888   
22     86.778700        9.155135    5.357143      0.000000        0.000000   
23      0.000000        0.000000    0.000000     37.123791        1.040440   
24     62.189427        3.476637    3.725490     86.977299        6.028866   
25      9.903508        0.638858    3.520833      0.000000        0.000000   
26      0.000000        0.000000    0.000000      0.000000        0.000000   
27     12.441004        1.535183    4.714286      0.000000        0.000000   
28      0.000000        0.000000    0.000000      0.000000        0.000000   
29     13.299359        2.051260    4.418605      0.000000        0.000000   

    C3-Fz.rate  C3-P3.Amplpp  C3-P3.PowmaxFR  C3-P3.rate  C3-Pz.Amplpp  \
0     3.106383     85.138423        3.443110    3.488372     20.852281   
1     3.612245     35.625319        5.203409    4.190476      0.000000   
2     0.000000      0.000000        0.000000    0.000000     16.948379   
3     0.000000     71.346781       15.783404    4.285714      0.000000   
4     6.521739     49.404292        4.065491    3.191489     61.498469   
5     4.000000      0.000000        0.000000    0.000000     11.723368   
6     4.477612     25.211380        3.782963    2.803738     29.287929   
7     0.000000      0.000000        0.000000    0.000000     42.511741   
8     2.238806     14.792310        0.600836    1.402439      0.000000   
9     4.000000      7.136024        0.589795    2.092593     24.670138   
10    1.486486      0.000000        0.000000    0.000000     13.426402   
11    3.703704     56.553460       11.529940    3.409091     22.668973   
12    4.918033     45.817162        5.832659    5.357143      0.000000   
13    0.000000     27.000300        0.754811    2.574074     34.766133   
14    3.658537     16.999301        2.268107    3.703704     22.386139   
15    0.000000     17.285665        3.041839    3.846154      0.000000   
16    0.000000     38.485147        2.838811    1.490909      8.429258   
17    0.000000      0.000000        0.000000    0.000000      0.000000   
18    3.333333     62.247921        2.288620    3.800000     61.549940   
19    0.000000      6.955895        0.960100    1.968254      0.000000   
20    3.934783     17.302728   

In [91]:
kms = KMeans(n_clusters=20, random_state=1).fit(final_data_frame_s[list(final_data_frame_s.iloc[:, :156])])
final_data_frame_s['Cluster'] = kms.labels_




/opt/homebrew/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [92]:
for i in range(156):
    final_data_frame_s[f'Cluster Centroid D{i}'] = final_data_frame_s['Cluster'].apply(lambda label: kms.cluster_centers_[label][i])
final_data_frame_s

C3-Cz.Amplpp  C3-Cz.PowmaxFR  C3-Cz.rate  C3-Fz.Amplpp  C3-Fz.PowmaxFR  \
0      10.771740        1.759448    2.553571     11.269735        1.699437   
1     196.669607       22.868967    6.047619     64.762088        6.231080   
2       0.000000        0.000000    0.000000      0.000000        0.000000   
3       0.000000        0.000000    0.000000      0.000000        0.000000   
4      28.581092        3.163530    3.163265     49.840620        6.736548   
5       0.000000        0.000000    0.000000     12.753706        2.237521   
6      18.703224        3.219575    1.859375     18.940291        2.821125   
7       0.000000        0.000000    0.000000      0.000000        0.000000   
8      14.223828        2.123832    1.612903     15.903879        2.717828   
9      25.743377        3.482564    3.333333     29.882885        6.848453   
10      0.000000        0.000000    0.000000     10.850524        1.891749   
11     25.761279        0.834857    1.418605     40.739765       13.604004   
12     48.959123        3.510763    0.964706     43.662376        5.838032   
13     16.239587        2.219290    1.075949      0.000000        0.000000   
14     29.133594        9.877290    2.830189     32.279609        7.609799   
15      0.000000        0.000000    0.000000      0.000000        0.000000   
16     11.607268        1.461668    2.490909      0.000000        0.000000   
17      0.000000        0.000000    0.000000      0.000000        0.000000   
18     63.138583        3.994395    1.373134     88.142041        8.200465   
19      0.000000        0.000000    0.000000      0.000000        0.000000   
20      0.000000        0.000000    0.000000     13.157727        1.487593   
21    309.744112       18.020033    4.928571    326.130958       15.340888   
22     86.778700        9.155135    5.357143      0.000000        0.000000   
23      0.000000        0.000000    0.000000     37.123791        1.040440   
24     62.189427        3.476637    3.725490     86.977299        6.028866   
25      9.903508        0.638858    3.520833      0.000000        0.000000   
26      0.000000        0.000000    0.000000      0.000000        0.000000   
27     12.441004        1.535183    4.714286      0.000000        0.000000   
28      0.000000        0.000000    0.000000      0.000000        0.000000   
29     13.299359        2.051260    4.418605      0.000000        0.000000   

    C3-Fz.rate  C3-P3.Amplpp  C3-P3.PowmaxFR  C3-P3.rate  C3-Pz.Amplpp  \
0     3.106383     85.138423        3.443110    3.488372     20.852281   
1     3.612245     35.625319        5.203409    4.190476      0.000000   
2     0.000000      0.000000        0.000000    0.000000     16.948379   
3     0.000000     71.346781       15.783404    4.285714      0.000000   
4     6.521739     49.404292        4.065491    3.191489     61.498469   
5     4.000000      0.000000        0.000000    0.000000     11.723368   
6     4.477612     25.211380        3.782963    2.803738     29.287929   
7     0.000000      0.000000        0.000000    0.000000     42.511741   
8     2.238806     14.792310        0.600836    1.402439      0.000000   
9     4.000000      7.136024        0.589795    2.092593     24.670138   
10    1.486486      0.000000        0.000000    0.000000     13.426402   
11    3.703704     56.553460       11.529940    3.409091     22.668973   
12    4.918033     45.817162        5.832659    5.357143      0.000000   
13    0.000000     27.000300        0.754811    2.574074     34.766133   
14    3.658537     16.999301        2.268107    3.703704     22.386139   
15    0.000000     17.285665        3.041839    3.846154      0.000000   
16    0.000000     38.485147        2.838811    1.490909      8.429258   
17    0.000000      0.000000        0.000000    0.000000      0.000000   
18    3.333333     62.247921        2.288620    3.800000     61.549940   
19    0.000000      6.955895        0.960100    1.968254      0.000000   
20    3.934783     17.302728   

In [93]:
features = final_data_frame_s.columns.tolist()[0:156]
print(f"Features: \n{features}")


centroids = kms.cluster_centers_
print(f"Centroids \n{centroids}")

Features: 
['C3-Cz.Amplpp', 'C3-Cz.PowmaxFR', 'C3-Cz.rate', 'C3-Fz.Amplpp', 'C3-Fz.PowmaxFR', 'C3-Fz.rate', 'C3-P3.Amplpp', 'C3-P3.PowmaxFR', 'C3-P3.rate', 'C3-Pz.Amplpp', 'C3-Pz.PowmaxFR', 'C3-Pz.rate', 'C4-Cz.Amplpp', 'C4-Cz.PowmaxFR', 'C4-Cz.rate', 'C4-Fz.Amplpp', 'C4-Fz.PowmaxFR', 'C4-Fz.rate', 'C4-P4.Amplpp', 'C4-P4.PowmaxFR', 'C4-P4.rate', 'C4-Pz.Amplpp', 'C4-Pz.PowmaxFR', 'C4-Pz.rate', 'Cz-Pz.Amplpp', 'Cz-Pz.PowmaxFR', 'Cz-Pz.rate', 'F3-C3.Amplpp', 'F3-C3.PowmaxFR', 'F3-C3.rate', 'F3-Cz.Amplpp', 'F3-Cz.PowmaxFR', 'F3-Cz.rate', 'F3-Fz.Amplpp', 'F3-Fz.PowmaxFR', 'F3-Fz.rate', 'F4-C4.Amplpp', 'F4-C4.PowmaxFR', 'F4-C4.rate', 'F4-Cz.Amplpp', 'F4-Cz.PowmaxFR', 'F4-Cz.rate', 'F4-Fz.Amplpp', 'F4-Fz.PowmaxFR', 'F4-Fz.rate', 'F7-C3.Amplpp', 'F7-C3.PowmaxFR', 'F7-C3.rate', 'F7-F3.Amplpp', 'F7-F3.PowmaxFR', 'F7-F3.rate', 'F7-T3.Amplpp', 'F7-T3.PowmaxFR', 'F7-T3.rate', 'F8-C4.Amplpp', 'F8-C4.PowmaxFR', 'F8-C4.rate', 'F8-F4.Amplpp', 'F8-F4.PowmaxFR', 'F8-F4.rate', 'F8-T4.Amplpp', 'F8-T4.Powma

In [94]:
sorted_centroid_features_idx = centroids.argsort(axis=1)[:,::-1]
print(f"Sorted Feature/Dimension Indexes for Each Centroid in Descending Order: \n{sorted_centroid_features_idx}")

print()

sorted_centroid_features_values = np.take_along_axis(centroids, sorted_centroid_features_idx, axis=1)
print(f"Sorted Feature/Dimension Values for Each Centroid in Descending Order: \n{sorted_centroid_features_values}")

Sorted Feature/Dimension Indexes for Each Centroid in Descending Order: 
[[ 99  27  57 ... 146  88  95]
 [144 138 123 ... 143  85  25]
 [ 45  51 108 ...  95  70  25]
 ...
 [120   6 144 ...  58  59 128]
 [150 126 129 ...  90  91   0]
 [123 117 120 ...  40  39 145]]

Sorted Feature/Dimension Values for Each Centroid in Descending Order: 
[[5.20885694e+01 5.02743501e+01 4.74072332e+01 ... 1.02500000e+00
  9.17425436e-01 8.65079365e-01]
 [1.31364785e+03 1.29281875e+03 1.28687557e+03 ... 3.40000000e+00
  3.11200568e+00 2.70251268e+00]
 [3.30547048e+02 3.25404609e+02 3.02660989e+02 ... 2.33870968e+00
  2.09440969e+00 1.95734844e+00]
 ...
 [1.32143203e+02 8.51384234e+01 8.17994011e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [7.71027928e+01 7.44921183e+01 7.43027537e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.00072680e+02 9.64725773e+01 9.54416510e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [95]:
first_features_in_centroid_1 = centroids[0][sorted_centroid_features_idx[0]]
centroids

array([[ 39.04635864,   6.69402645,   1.89744728, ...,  12.89517111,
          1.90644757,   1.53061224],
       [309.7441118 ,  18.02003264,   4.92857143, ..., 500.22808373,
         24.23421127,   4.41860465],
       [ 62.18942681,   3.47663672,   3.7254902 , ..., 159.02598182,
         10.50438651,   3.8627451 ],
       ...,
       [ 10.7717403 ,   1.75944828,   2.55357143, ...,  10.94395404,
          1.85452008,   2.63333333],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  9.90350822,   0.63885834,   3.52083333, ...,  18.54356183,
          1.04030712,   2.84782609]])

In [100]:
final_data_frame_s.loc[[4,5], [""]] += final_data_frame_s.loc[[4,5], ["Feature1"]] + 30

NameError: name 'df' is not defined

In [96]:
print(list(
        zip(
            [features[feature] for feature in sorted_centroid_features_idx[0]], 
            first_features_in_centroid_1
        )
    ))

[('P4-Cz.Amplpp', 52.08856939407134), ('F3-C3.Amplpp', 50.274350108275996), ('F8-F4.Amplpp', 47.40723321651595), ('Cz-Pz.Amplpp', 45.787046180093455), ('Fp1-F3.Amplpp', 44.497297506654), ('C4-P4.Amplpp', 44.25076616032895), ('F8-C4.Amplpp', 41.54872558625935), ('F7-F3.Amplpp', 41.02645459280225), ('T5-C3.Amplpp', 40.4297741777552), ('C3-Cz.Amplpp', 39.0463586372953), ('F3-Cz.Amplpp', 38.7512457477407), ('F4-C4.Amplpp', 38.197322583011), ('C3-Fz.Amplpp', 37.9709925354577), ('F3-Fz.Amplpp', 37.8496914544358), ('T3-F3.Amplpp', 36.30588311266755), ('Fp2-F4.Amplpp', 35.73626771844725), ('T4-F4.Amplpp', 34.06201875709615), ('F4-Fz.Amplpp', 33.9180736592465), ('F7-C3.Amplpp', 33.91744591718064), ('Fp1-Fp2.Amplpp', 31.889312556192202), ('T3-C3.Amplpp', 31.740531848209248), ('C3-P3.Amplpp', 31.4082313653387), ('F4-Cz.Amplpp', 31.0301912671226), ('Fp1-Fz.Amplpp', 30.5509741239181), ('F8-T4.Amplpp', 30.0837479416652), ('Fp2-Fz.Amplpp', 29.61491326134915), ('Fp2-F8.Amplpp', 29.448758667161197), ('

In [97]:
my_dict = {}
keys = []
values = []
for i in range(1, 20):
    keys.append(i)

for i in range(20):
    values.append(0)

for i in keys:
    my_dict[0] = 1
    my_dict[i] = values[i]

my_dict

print(final_data_frame_s['Cluster'].value_counts())
final_data_frame_s['Binary Cluster 0'] = final_data_frame_s['Cluster'].map(my_dict)
print("\n", final_data_frame_s["Binary Cluster 0"].value_counts())


    

7     8
8     2
16    2
0     2
17    1
4     1
6     1
19    1
2     1
11    1
14    1
1     1
18    1
12    1
5     1
10    1
3     1
13    1
15    1
9     1
Name: Cluster, dtype: int64

 0    28
1     2
Name: Binary Cluster 0, dtype: int64


In [99]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=1)
clf.fit(final_data_frame_s[(list(final_data_frame_s.iloc[:,:156]))].values, final_data_frame_s["Binary Cluster 0"].values)

# Index sort the most important features
sorted_feature_weight_idxes = np.argsort(clf.feature_importances_)[::-1] # Reverse sort

# Get the most important features names and weights
most_important_features = np.take_along_axis(
    np.array(final_data_frame_s.iloc[:, :].columns.tolist()), 
    sorted_feature_weight_idxes, axis=0)
most_important_weights = np.take_along_axis(
    np.array(clf.feature_importances_), 
    sorted_feature_weight_idxes, axis=0)

# Show
list(zip(most_important_features, most_important_weights))

[('Fp2-Fz.rate', 0.09017187843224264),
 ('F8-T4.rate', 0.07192415019211433),
 ('P3-Cz.rate', 0.04717864300713325),
 ('T3-C3.rate', 0.04401822676393258),
 ('C4-P4.Amplpp', 0.04009068334911032),
 ('F4-C4.rate', 0.03853711186140476),
 ('Fp2-Fz.PowmaxFR', 0.035757730704318404),
 ('C3-Pz.PowmaxFR', 0.02851352444533383),
 ('F8-C4.rate', 0.02789616427741185),
 ('C3-P3.rate', 0.02730730675325793),
 ('C4-Cz.PowmaxFR', 0.02707283998450213),
 ('T4-P4.Amplpp', 0.024372187285786665),
 ('F4-Fz.PowmaxFR', 0.020886609834205108),
 ('C3-Cz.Amplpp', 0.02062385072846135),
 ('C4-P4.rate', 0.01704765594730725),
 ('F3-Cz.rate', 0.016321193335916313),
 ('C3-Cz.PowmaxFR', 0.01622971285892635),
 ('C4-Fz.PowmaxFR', 0.015590080300858492),
 ('T3-F3.PowmaxFR', 0.015179609232301996),
 ('T4-P4.PowmaxFR', 0.013539110594515473),
 ('C4-P4.PowmaxFR', 0.012569165086851318),
 ('F4-Cz.rate', 0.012093378614522138),
 ('F7-C3.PowmaxFR', 0.011964211402413645),
 ('T5-O1.rate', 0.011235955056179775),
 ('T6-O2.Amplpp', 0.011235955

In [ ]:
final_data_frame_s

In [ ]:
a = list(final_data_frame_s.iloc[:, 156])

In [ ]:
a.count(7)
    

In [ ]:
a

In [ ]:
p = []
for i in a:
    x = a.count(i)
    p.append(x)

